<li><a target="_blank" href="/tools">柒小工具箱</a></li>
<li><a target="_blank" href="/xuanxue">柒小玄学网</a></li>
<br>
<article>友情链接 -></article>
<ul style="padding-left:0px;">
    <li><a target="blank" href="https://bantina.github.io/">Bantina</a></li>
</ul>

<!-- <ul style="margin:0;padding:0;">
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=298 height=52 src="//music.163.com/outchain/player?type=0&id=368095995&auto=1&height=32"></iframe>
</ul> -->